import { FormSchema } from '@/services';

export const getQueryProcessFormSchema = () =>
  ({
    components: [
      {
        text: '# query process instances\n\nfill in the details below to query process instances.',
        type: 'text',
        id: 'field_intro_process',
      },
      {
        label: 'Start',
        key: 'start',
        type: 'textfield',
        id: 'Field_start',
      },
      {
        label: 'Size',
        key: 'size',
        type: 'textfield',
        id: 'Field_size',
      },
      {
        label: 'Sort',
        key: 'sort',
        type: 'textfield',
        id: 'Field_sort',
      },
      {
        label: 'Order',
        key: 'order',
        type: 'textfield',
        id: 'Field_order',
      },
      {
        label: 'Process Instance ID',
        key: 'processInstanceId',
        type: 'textfield',
        id: 'Field_processInstanceId',
      },
      {
        label: 'Process Instance Name',
        key: 'processInstanceName',
        type: 'textfield',
        id: 'Field_processInstanceName',
      },
      {
        label: 'Process Instance Name Like',
        key: 'processInstanceNameLike',
        type: 'textfield',
        id: 'Field_processInstanceNameLike',
      },
      {
        label: 'Process Business Key',
        key: 'processBusinessKey',
        type: 'textfield',
        id: 'Field_processBusinessKey',
      },
      {
        label: 'Process Business Status',
        key: 'processBusinessStatus',
        type: 'textfield',
        id: 'Field_processBusinessStatus',
      },
      {
        label: 'Process Definition ID',
        key: 'processDefinitionId',
        type: 'textfield',
        id: 'Field_processDefinitionId',
      },
      {
        label: 'Process Definition Key',
        key: 'processDefinitionKey',
        type: 'textfield',
        id: 'Field_processDefinitionKey',
      },
      {
        label: 'Process Definition Name',
        key: 'processDefinitionName',
        type: 'textfield',
        id: 'Field_processDefinitionName',
      },
      {
        label: 'Process Definition Version',
        key: 'processDefinitionVersion',
        type: 'textfield',
        id: 'Field_processDefinitionVersion',
      },
      {
        label: 'Root Scope ID',
        key: 'rootScopeId',
        type: 'textfield',
        id: 'Field_rootScopeId',
      },
      {
        label: 'Parent Scope ID',
        key: 'parentScopeId',
        type: 'textfield',
        id: 'Field_parentScopeId',
      },
      {
        label: 'Deployment ID',
        key: 'deploymentId',
        type: 'textfield',
        id: 'Field_deploymentId',
      },
      {
        label: 'Super Process Instance ID',
        key: 'superProcessInstanceId',
        type: 'textfield',
        id: 'Field_superProcessInstanceId',
      },
      {
        label: 'Sub Process Instance ID',
        key: 'subProcessInstanceId',
        type: 'textfield',
        id: 'Field_subProcessInstanceId',
      },
      {
        label: 'Exclude Subprocesses',
        key: 'excludeSubprocesses',
        type: 'checkbox',
        id: 'Field_excludeSubprocesses',
      },
      {
        label: 'Active Activity ID',
        key: 'activeActivityId',
        type: 'textfield',
        id: 'Field_activeActivityId',
      },
      {
        label: 'Involved User',
        key: 'involvedUser',
        type: 'textfield',
        id: 'Field_involvedUser',
      },
      {
        label: 'Started By',
        key: 'startedBy',
        type: 'textfield',
        id: 'Field_startedBy',
      },
      {
        label: 'Started Before',
        key: 'startedBefore',
        type: 'datetime',
        id: 'Field_startedBefore',
      },
      {
        label: 'Started After',
        key: 'startedAfter',
        type: 'datetime',
        id: 'Field_startedAfter',
      },
      {
        label: 'Suspended',
        key: 'suspended',
        type: 'checkbox',
        id: 'Field_suspended',
      },
      {
        label: 'Include Process Variables',
        key: 'includeProcessVariables',
        type: 'checkbox',
        id: 'Field_includeProcessVariables',
      },
      {
        label: 'Callback ID',
        key: 'callbackId',
        type: 'textfield',
        id: 'Field_callbackId',
      },
      {
        label: 'Callback Type',
        key: 'callbackType',
        type: 'textfield',
        id: 'Field_callbackType',
      },
      {
        label: 'Tenant ID',
        key: 'tenantId',
        type: 'textfield',
        id: 'Field_tenantId',
      },
      {
        label: 'Without Tenant ID',
        key: 'withoutTenantId',
        type: 'checkbox',
        id: 'Field_withoutTenantId',
      },
    ],
    schemaVersion: 18,
    type: 'default',
    id: 'Form_0khm3ai',
    versionTag: 'dd',
  }) as FormSchema;
