spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:14403/realms/kinetiqBP/protocol/openid-connect/certs"

server:
  port: 18403

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:17403/eureka/
    fetch-registry: true
    register-with-eureka: true